#!/usr/bin/env python3
"""Majestic menu — simple orchestrator for release scripts."""

from __future__ import annotations

import json
import os
import shutil
import subprocess
import sys
import zipfile
from datetime import datetime
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
MAJESTIC_DIR = ROOT / "scripts" / "majestic"
MAJESTIC_PS1 = MAJESTIC_DIR / "majestic.ps1"
BUILD_TOOLCHAIN_PS1 = ROOT / "scripts" / "build-foundry-toolchain.ps1"
OUT_DIR = ROOT / ".majestic-out"
BACKUP_ROOT = ROOT / ".majestic-backup"
RUNTIME_DIR = ROOT / "src-tauri" / "runtime"
UNLOCK_FILE = MAJESTIC_DIR / ".majestic-enabled"
PARANOID_VERSION = 2

# Dir names skipped everywhere while walking the repo.
ALWAYS_SKIP_DIR_NAMES = frozenset({
    "node_modules",
    ".cargo",
    "dist",
    "dist-ssr",
    "__pycache__",
    ".venv",
    "venv",
    "deps",
    "incremental",
    ".fingerprint",
    ".majestic-out",
    ".majestic-backup",
    "models",
    ".git",
    ".vscode",
    ".idea",
    "opencode.db",
    "engines",  # llama.cpp source trees — git/foundry re-clone
    "work",     # disposable foundry cmake trees
})

# Under src-tauri/target/debug — only foundry artifacts + app config (not Rust junk).
DEBUG_TARGET_KEEP = frozenset({"foundry", "config"})

SKIP_FILE_SUFFIXES = frozenset({
    ".gguf",
    ".bin",
    ".pdb",  # debug symbols — not needed to run/restore binaries
})


def clear_screen() -> None:
    os.system("cls" if os.name == "nt" else "clear")


def read_version() -> str:
    tauri_conf = ROOT / "src-tauri" / "tauri.conf.json"
    try:
        data = json.loads(tauri_conf.read_text(encoding="utf-8"))
        return str(data.get("version", "?"))
    except (OSError, json.JSONDecodeError):
        return "?"


def run_powershell_script(script: Path, *extra_args: str) -> int:
    if not script.is_file():
        print(f"[majestic] Missing script: {script}")
        return 1

    args = [
        "powershell",
        "-NoProfile",
        "-ExecutionPolicy",
        "Bypass",
        "-File",
        str(script),
        *extra_args,
    ]

    print()
    print(f"[majestic] Running: {' '.join(args)}")
    print("-" * 60)

    completed = subprocess.run(args, cwd=ROOT)
    print("-" * 60)
    return completed.returncode


def run_majestic(mode: str, *, dry_run: bool = False) -> int:
    if not MAJESTIC_PS1.is_file():
        print(f"[majestic] Missing script: {MAJESTIC_PS1}")
        return 1

    args = [
        "powershell",
        "-NoProfile",
        "-ExecutionPolicy",
        "Bypass",
        "-File",
        str(MAJESTIC_PS1),
        "-Mode",
        mode,
    ]
    if dry_run:
        args.append("-DryRun")

    print()
    print(f"[majestic] Running: {' '.join(args)}")
    print("-" * 60)

    completed = subprocess.run(args, cwd=ROOT)
    print("-" * 60)
    return completed.returncode


def rel_to_root(path: Path) -> Path | None:
    try:
        return path.resolve().relative_to(ROOT.resolve())
    except ValueError:
        return None


def prune_walk_dirs(current: Path, dirs: list[str]) -> None:
    rel = rel_to_root(current)
    if rel is None:
        dirs.clear()
        return

    rel_parts = rel.parts
    kept: list[str] = []

    for name in dirs:
        if name in ALWAYS_SKIP_DIR_NAMES:
            continue

        # Dev runtime mirror at repo root (duplicate of src-tauri/runtime).
        if len(rel_parts) == 0 and name == "target":
            continue

        # NSIS staging tree — regenerated by prepare-release-runtime.
        if rel_parts == ("src-tauri",) and name == "runtime-bundle":
            continue

        if rel_parts == ("src-tauri", "target"):
            if name != "debug":
                continue
        elif rel_parts == ("src-tauri", "target", "debug"):
            if name not in DEBUG_TARGET_KEEP:
                continue
        elif rel_parts == ("src-tauri", "target", "debug", "foundry"):
            # Sacred builds only — not llama.cpp source trees (git + foundry re-clone).
            if name != "artifacts":
                continue
        elif rel_parts[:3] == ("src-tauri", "target", "release"):
            continue

        if name == "gen" and rel_parts[:1] == ("src-tauri",):
            continue

        kept.append(name)

    dirs[:] = kept


def should_skip_file(path: Path) -> bool:
    if path.suffix.lower() in SKIP_FILE_SUFFIXES:
        return True
    rel = rel_to_root(path)
    if rel is None:
        return True
    if rel.parts[:3] == ("src-tauri", "target", "release"):
        return True
    # Belt-and-suspenders: never pack llama source or cmake work trees.
    if "foundry" in rel.parts:
        if "engines" in rel.parts or "work" in rel.parts:
            return True
    return False


def backup_paranoid() -> int:
    stamp = datetime.now().strftime("%Y%m%d-%H%M%S")
    archive = BACKUP_ROOT / f"paranoid-{stamp}.zip"
    BACKUP_ROOT.mkdir(parents=True, exist_ok=True)

    print(f"[majestic] PARANOID backup v{PARANOID_VERSION} starting...")
    print("[majestic] Includes: source, src-tauri/runtime, foundry/artifacts ONLY (sacred exes)")
    print("[majestic] Skips: foundry/engines, work/, runtime-bundle, target/, .pdb, node_modules, Rust caches")
    print(f"[majestic] Writing {archive}")
    print()

    file_count = 0
    engines_leaked = 0
    started = datetime.now()

    # STORE = no compression — faster; exe/dll barely shrink anyway.
    with zipfile.ZipFile(archive, "w", zipfile.ZIP_STORED) as zf:
        for dirpath, dirnames, filenames in os.walk(ROOT):
            current = Path(dirpath)
            prune_walk_dirs(current, dirnames)

            for filename in filenames:
                filepath = current / filename
                if should_skip_file(filepath):
                    continue
                arcname = filepath.relative_to(ROOT).as_posix()
                if "/foundry/engines/" in arcname or "/foundry/work/" in arcname:
                    engines_leaked += 1
                    continue
                try:
                    zf.write(filepath, arcname)
                    file_count += 1
                    if file_count % 500 == 0:
                        print(f"[majestic]   ...{file_count} files")
                except OSError as exc:
                    print(f"[majestic]   skip {arcname}: {exc}")

    elapsed = (datetime.now() - started).total_seconds()
    size_mb = archive.stat().st_size / (1024 * 1024)
    print()
    print(f"[majestic] PARANOID v{PARANOID_VERSION} OK: {archive}")
    print(f"[majestic] {file_count} files | {size_mb:.1f} MB | {elapsed:.1f}s")
    if engines_leaked:
        print(f"[majestic] WARNING: blocked {engines_leaked} engines/work paths (should be 0 leaks in zip)")
    if file_count > 2500:
        print("[majestic] WARNING: file count high — old backup was ~8000; expect ~1500. Re-run from repo Majestic.bat")
    print("[majestic] Restore: unzip over repo root (exclude target/release junk)")
    return 0


def folder_size_mb(path: Path) -> float:
    total = 0
    for root, _dirs, files in os.walk(path):
        for name in files:
            try:
                total += (Path(root) / name).stat().st_size
            except OSError:
                pass
    return total / (1024 * 1024)


def backup_runtime() -> int:
    if not RUNTIME_DIR.is_dir():
        print(f"[majestic] Nothing to back up: {RUNTIME_DIR} missing")
        return 1

    stamp = datetime.now().strftime("%Y%m%d-%H%M%S")
    dest = BACKUP_ROOT / f"runtime-{stamp}"
    BACKUP_ROOT.mkdir(parents=True, exist_ok=True)

    print(f"[majestic] Backing up runtime -> {dest}")
    shutil.copytree(RUNTIME_DIR, dest)
    size_mb = folder_size_mb(dest)
    print(f"[majestic] Backup OK ({size_mb:.1f} MB)")
    print("[majestic] Restore: copy that folder back over src-tauri/runtime/")
    return 0


def offer_pack_backup() -> None:
    answer = input("Backup runtime before pack? [Y/n]: ").strip().lower()
    if answer in ("", "y", "yes"):
        backup_runtime()

    paranoid = input("Paranoid full backup too? (~15s, saves foundry+toolchain) [y/N]: ").strip().lower()
    if paranoid in ("y", "yes"):
        backup_paranoid()


def open_output_folder() -> None:
    if not OUT_DIR.is_dir():
        print(f"[majestic] Output folder not found yet: {OUT_DIR}")
        print("[majestic] Run PACK first.")
        return
    os.startfile(OUT_DIR)  # type: ignore[attr-defined]


def open_backup_folder() -> None:
    if not BACKUP_ROOT.is_dir():
        print(f"[majestic] No backups yet: {BACKUP_ROOT}")
        return
    os.startfile(BACKUP_ROOT)  # type: ignore[attr-defined]


def print_header() -> None:
    version = read_version()
    unlock = "ON" if UNLOCK_FILE.is_file() else "OFF"
    staged = "yes" if OUT_DIR.is_dir() and any(OUT_DIR.iterdir()) else "no"
    print("=" * 60)
    print("  MAJESTIC  -  Blackwell Ops release robot")
    print("=" * 60)
    print(f"  Version: {version}  |  Ship unlock: {unlock}  |  Staged: {staged}")
    print(f"  Repo: {ROOT}")
    print("=" * 60)
    print()
    print("  1  CHECK   - am I ready to ship? (safe)")
    print("  2  PACK    - mirror, bundle, build, stage installer")
    print("  3  SHIP    - upload to GitHub (asks YES)")
    print(" 10  BUMP    - patch+1 across all version files (asks YES)")
    print()
    print("  4  Pack dry-run")
    print("  5  Ship dry-run")
    print("  6  Open .majestic-out folder")
    print("  7  Backup runtime (configs + binaries)")
    print("  8  Open .majestic-backup folder")
    print("  9  PARANOID backup (project zip, keeps foundry+toolchain)")
    print(" 11  TOOLCHAIN - rebuild + pack toolchain.7z for GitHub upload")
    print()
    print("  0  Exit")
    print()


def main() -> int:
    if os.name != "nt":
        print("[majestic] This menu is tuned for Windows.")
    if not (ROOT / "package.json").is_file():
        print(f"[majestic] Could not find repo root: {ROOT}")
        return 1

    while True:
        clear_screen()
        print_header()
        choice = input("Pick a number: ").strip()

        if choice == "0":
            print("Bye.")
            return 0

        if choice == "1":
            code = run_majestic("check")
        elif choice == "2":
            offer_pack_backup()
            code = run_majestic("pack")
        elif choice == "3":
            paranoid = input("Paranoid backup before ship? [y/N]: ").strip().lower()
            if paranoid in ("y", "yes"):
                backup_paranoid()
            code = run_majestic("ship")
        elif choice == "4":
            code = run_majestic("pack", dry_run=True)
        elif choice == "5":
            code = run_majestic("ship", dry_run=True)
        elif choice == "6":
            open_output_folder()
            code = 0
        elif choice == "7":
            code = backup_runtime()
        elif choice == "8":
            open_backup_folder()
            code = 0
        elif choice == "9":
            code = backup_paranoid()
        elif choice == "10":
            code = run_majestic("bump")
        elif choice == "11":
            repack = input("Repack existing tree only (no host VS/CUDA)? [y/N]: ").strip().lower()
            if repack in ("y", "yes"):
                code = run_powershell_script(BUILD_TOOLCHAIN_PS1, "-RepackOnly")
            else:
                code = run_powershell_script(BUILD_TOOLCHAIN_PS1)
        else:
            print("Unknown choice. Use 0-11.")
            code = 1

        print()
        if code == 0:
            print("[majestic] Done.")
        else:
            print(f"[majestic] Finished with exit code {code}.")
        input("Press Enter to return to menu...")


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except KeyboardInterrupt:
        print("\nBye.")
        raise SystemExit(0) from None